<div id="content">
    <div class="container">
        <div class="block">
        <div class="post-content"><h3><?php echo $this->lang->line('terms_1');?></h3>
<p><?php echo $this->lang->line('terms_2');?></p>
<p><strong><?php echo $this->lang->line('terms_3');?></strong></p>
<p style="padding-left: 30px;"><?php echo $this->lang->line('terms_4');?></p>
<p><strong><?php echo $this->lang->line('terms_5');?></strong></p>
<p style="padding-left: 30px;"><?php echo $this->lang->line('terms_6');?></p>
<p><strong><?php echo $this->lang->line('terms_7');?></strong></p>
<p style="padding-left: 30px;"><?php echo $this->lang->line('terms_8');?></p>
<p><strong>4. Warranty; Disclaimer</strong></p>
<p style="padding-left: 30px;">The Sample Network warrants that: (i) it will provide its services hereunder in a professional and workmanlike manner; and (ii) the third parties with which it contracts to assist it in obtaining respondents for surveys are required by their agreements with The Sample Network to comply with the federal CAN-SPAM Act. WITH THE EXCEPTION OF THE PRECEDING WARRANTY, THE SAMPLE NETWORK MAKES NO WARRANTY WITH RESPECT TO ANY MATTER INCLUDING, WITHOUT LIMITATION, ITS SERVICES AND DELIVERABLES HEREUNDER, AND EXPRESSLY DISCLAIMS ALL OTHER WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF NONINFRINGEMENT, TITLE, MERCHANTABILITY, FITNESS FOR ANY PARTICULAR PURPOSE, AND ANY REPRESENTATION OR WARRANTY REGARDING THE PERFORMANCE, AVAILABILITY OR FUNCTIONALITY OF ANY ASPECT OF THE SERVICES OR DELIVERABLES HEREUNDER.</p>
<p><strong>5. Limitations of Liability</strong></p>
<p style="padding-left: 30px;">In the event that The Sample Network fails to deliver any services or deliverables, including completed surveys, in accordance with, and within the time period(s) set forth in, the applicable Request, or in the event of any other failure, technical or otherwise of such services or deliverables, the entire liability of The Sample Network and the exclusive remedy of Client shall be limited to the price reduction and future credit set forth in Paragraph 3 above. IN NO EVENT SHALL THE SAMPLE NETWORK BE LIABLE UNDER THIS AGREEMENT FOR ANY CONSEQUENTIAL, SPECIAL, INDIRECT OR PUNITIVE DAMAGES INCLUDING, WITHOUT LIMITATION, LOST PROFITS, WHETHER BASED IN CONTRACT, TORT OR OTHERWISE, EVEN IF THE SAMPLE NETWORK HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY. IN NO EVENT SHALL THE SAMPLE NETWORK’S AGGREGATE LIABILITY UNDER THIS AGREEMENT FOR ANY CLAIM EXCEED THE AGGREGATE AMOUNT OF THE ORDER. Without limiting the foregoing, The Sample Network shall have no liability for any failure or delay resulting from any governmental action, fire, flood, insurrection, earthquake, power failure, riot, explosion, embargo, strikes whether legal or illegal, labor or material shortage, transportation interruption of any kind, work slowdown or any other condition affecting production or delivery in any manner beyond the control of The Sample Network. Client acknowledges that The Sample Network has entered into this Agreement in reliance upon the limitations of liability set forth herein and that the same is an essential basis of the bargain between the parties.</p>
<p><strong>6. Miscellaneous</strong></p>
<p style="padding-left: 30px;">This Agreement and the Request constitute the entire agreement of the parties with respect to the subject matter of the Request. This Agreement shall be governed by and construed in accordance with the laws of the State of New Jersey, without giving effect to principles of conflicts of law. Any dispute arising out of or relating to this Agreement shall be brought exclusively in the federal or state courts located in the State of New Jersey, the jurisdiction and venue of which the parties irrevocably consent to for this purpose. This Agreement may be amended only by a writing executed by a duly authorized representative of each party. Client shall make no public announcement regarding the existence or content of the Request without The Sample Network’s prior written approval, which approval shall not be unreasonably withheld. Any notices under this Agreement shall be sent to the addresses set forth in the Request (or in a separate writing) by facsimile or nationally-recognized express delivery service and deemed given upon receipt. The waiver of any breach or default of this Agreement will not constitute a waiver of any subsequent breach or default, and will not act to amend or negate the rights of the waiving party. If any provision contained in this Agreement is determined to be invalid, illegal or unenforceable in any respect under any applicable law, then such provision will be severed and replaced with a new provision that most closely reflects the original intention of the parties, and the remaining provisions of this Agreement will remain in full force and effect.</p>
<p style="padding-left: 30px;">By submitting its Request to The Sample Network, Client assent and agrees to these Standard Terms.</p>
</div>
        </div>
    </div>
</div>    